# My fonts:
#
[font]
size = 12
normal  = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
